import { Message } from "@/pages/Chat/types";

export const MOCK_CHATS = [
  {
    id: 1,
    firstName: "Goldi",
    lastName: "Cotgrove",
    email: "gcotgrove0@addthis.com",
    profilePhoto: "https://robohash.org/rerumnameius.png?size=50x50&set=set1",
    lastActivityAt: "1710444817000",
    lastMessage:
      "etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at",
    hasSeenLastMessage: true,
    unreadCount: 55,
  },
  {
    id: 2,
    firstName: "Eda",
    lastName: "Baldacchino",
    email: "ebaldacchino1@theglobeandmail.com",
    profilePhoto:
      "https://robohash.org/eumlaboriosamveniam.png?size=50x50&set=set1",
    lastActivityAt: "1693449387000",
    lastMessage:
      "justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante",
    hasSeenLastMessage: false,
    unreadCount: 6,
  },
  {
    id: 3,
    firstName: "Berk",
    lastName: "Spiller",
    email: "bspiller2@theguardian.com",
    profilePhoto:
      "https://robohash.org/doloremqueullamqui.png?size=50x50&set=set1",
    lastActivityAt: "1706089018000",
    lastMessage:
      "aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt",
    hasSeenLastMessage: true,
    unreadCount: 18,
  },
  {
    id: 4,
    firstName: "Chickie",
    lastName: "Morilla",
    email: "cmorilla3@blogs.com",
    profilePhoto: "https://robohash.org/explicabononet.png?size=50x50&set=set1",
    lastActivityAt: "1711286685000",
    lastMessage:
      "sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at",
    hasSeenLastMessage: true,
    unreadCount: 43,
  },
  {
    id: 5,
    firstName: "Shannon",
    lastName: "Grellis",
    email: "sgrellis4@fema.gov",
    profilePhoto:
      "https://robohash.org/doloresreprehenderitoccaecati.png?size=50x50&set=set1",
    lastActivityAt: "1712628438000",
    lastMessage:
      "pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor",
    hasSeenLastMessage: true,
    unreadCount: 23,
  },
  {
    id: 6,
    firstName: "Cristabel",
    lastName: "Malkin",
    email: "cmalkin5@go.com",
    profilePhoto:
      "https://robohash.org/consequaturetconsequatur.png?size=50x50&set=set1",
    lastActivityAt: "1699667658000",
    lastMessage:
      "potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at",
    hasSeenLastMessage: false,
    unreadCount: 53,
  },
  {
    id: 7,
    firstName: "Dani",
    lastName: "Sustins",
    email: "dsustins6@wiley.com",
    profilePhoto: "https://robohash.org/utquiveritatis.png?size=50x50&set=set1",
    lastActivityAt: "1697996513000",
    lastMessage:
      "pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse",
    hasSeenLastMessage: true,
    unreadCount: 2,
  },
  {
    id: 8,
    firstName: "Gavra",
    lastName: "Dimnage",
    email: "gdimnage7@msn.com",
    profilePhoto:
      "https://robohash.org/occaecatiperferendiset.png?size=50x50&set=set1",
    lastActivityAt: "1711709588000",
    lastMessage:
      "erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse",
    hasSeenLastMessage: false,
    unreadCount: 12,
  },
  {
    id: 9,
    firstName: "Rodi",
    lastName: "Langabeer",
    email: "rlangabeer8@naver.com",
    profilePhoto:
      "https://robohash.org/mollitiapossimusreprehenderit.png?size=50x50&set=set1",
    lastActivityAt: "1708550715000",
    lastMessage:
      "neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet",
    hasSeenLastMessage: false,
    unreadCount: 93,
  },
  {
    id: 10,
    firstName: "Dane",
    lastName: "Short",
    email: "dshort9@yandex.ru",
    profilePhoto:
      "https://robohash.org/modisolutacupiditate.png?size=50x50&set=set1",
    lastActivityAt: "1717139481000",
    lastMessage:
      "ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis",
    hasSeenLastMessage: true,
    unreadCount: 44,
  },
  {
    id: 11,
    firstName: "Alex",
    lastName: "Dishmon",
    email: "adishmona@deviantart.com",
    profilePhoto:
      "https://robohash.org/sitmolestiaevoluptas.png?size=50x50&set=set1",
    lastActivityAt: "1723507084000",
    lastMessage:
      "nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo",
    hasSeenLastMessage: false,
    unreadCount: 74,
  },
  {
    id: 12,
    firstName: "Dixie",
    lastName: "Everington",
    email: "deveringtonb@irs.gov",
    profilePhoto: "https://robohash.org/sednisiea.png?size=50x50&set=set1",
    lastActivityAt: "1721530833000",
    lastMessage:
      "orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia",
    hasSeenLastMessage: false,
    unreadCount: 40,
  },
  {
    id: 13,
    firstName: "Conchita",
    lastName: "Iashvili",
    email: "ciashvilic@mapy.cz",
    profilePhoto:
      "https://robohash.org/perspiciatisasperioresminima.png?size=50x50&set=set1",
    lastActivityAt: "1698134814000",
    lastMessage:
      "ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia",
    hasSeenLastMessage: true,
    unreadCount: 19,
  },
  {
    id: 14,
    firstName: "Welsh",
    lastName: "Betser",
    email: "wbetserd@nymag.com",
    profilePhoto: "https://robohash.org/doloreetut.png?size=50x50&set=set1",
    lastActivityAt: "1717759496000",
    lastMessage:
      "volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales",
    hasSeenLastMessage: false,
    unreadCount: 25,
  },
  {
    id: 15,
    firstName: "Raul",
    lastName: "Esel",
    email: "resele@etsy.com",
    profilePhoto:
      "https://robohash.org/aquidemdistinctio.png?size=50x50&set=set1",
    lastActivityAt: "1718855227000",
    lastMessage:
      "parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi",
    hasSeenLastMessage: false,
    unreadCount: 2,
  },
  {
    id: 16,
    firstName: "Maynord",
    lastName: "Edgett",
    email: "medgettf@japanpost.jp",
    profilePhoto: "https://robohash.org/illumtotamnemo.png?size=50x50&set=set1",
    lastActivityAt: "1721963010000",
    lastMessage:
      "vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam",
    hasSeenLastMessage: false,
    unreadCount: 36,
  },
  {
    id: 17,
    firstName: "Colline",
    lastName: "McCathie",
    email: "cmccathieg@boston.com",
    profilePhoto:
      "https://robohash.org/expeditaquistempora.png?size=50x50&set=set1",
    lastActivityAt: "1723812157000",
    lastMessage:
      "non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie",
    hasSeenLastMessage: true,
    unreadCount: 41,
  },
  {
    id: 18,
    firstName: "Glenine",
    lastName: "Kernar",
    email: "gkernarh@reddit.com",
    profilePhoto:
      "https://robohash.org/voluptatemautemut.png?size=50x50&set=set1",
    lastActivityAt: "1699690858000",
    lastMessage:
      "augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet",
    hasSeenLastMessage: false,
    unreadCount: 33,
  },
  {
    id: 19,
    firstName: "Ophelie",
    lastName: "Fearby",
    email: "ofearbyi@businessweek.com",
    profilePhoto: "https://robohash.org/sitquieos.png?size=50x50&set=set1",
    lastActivityAt: "1719065485000",
    lastMessage:
      "tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue",
    hasSeenLastMessage: true,
    unreadCount: 22,
  },
  {
    id: 20,
    firstName: "Jana",
    lastName: "Madigan",
    email: "jmadiganj@quantcast.com",
    profilePhoto: "https://robohash.org/modiquamet.png?size=50x50&set=set1",
    lastActivityAt: "1698783264000",
    lastMessage:
      "et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor",
    hasSeenLastMessage: true,
    unreadCount: 70,
  },
  {
    id: 21,
    firstName: "Petunia",
    lastName: "Bome",
    email: "pbomek@google.com.br",
    profilePhoto: "https://robohash.org/etitaqueex.png?size=50x50&set=set1",
    lastActivityAt: "1693827140000",
    lastMessage:
      "rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci",
    hasSeenLastMessage: false,
    unreadCount: 77,
  },
  {
    id: 22,
    firstName: "Rab",
    lastName: "Vannikov",
    email: "rvannikovl@tinypic.com",
    profilePhoto: "https://robohash.org/dolorsedquia.png?size=50x50&set=set1",
    lastActivityAt: "1704220381000",
    lastMessage:
      "eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse",
    hasSeenLastMessage: true,
    unreadCount: 79,
  },
  {
    id: 23,
    firstName: "Erroll",
    lastName: "Raggatt",
    email: "eraggattm@youtube.com",
    profilePhoto:
      "https://robohash.org/dignissimosidreiciendis.png?size=50x50&set=set1",
    lastActivityAt: "1719594797000",
    lastMessage: "eu sapien cursus vestibulum proin eu mi nulla ac enim in",
    hasSeenLastMessage: false,
    unreadCount: 1,
  },
  {
    id: 24,
    firstName: "Clementia",
    lastName: "Biesterfeld",
    email: "cbiesterfeldn@123-reg.co.uk",
    profilePhoto:
      "https://robohash.org/optionumquamsit.png?size=50x50&set=set1",
    lastActivityAt: "1712047022000",
    lastMessage:
      "primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi",
    hasSeenLastMessage: false,
    unreadCount: 76,
  },
  {
    id: 25,
    firstName: "Mame",
    lastName: "Inglesfield",
    email: "minglesfieldo@51.la",
    profilePhoto:
      "https://robohash.org/architectoquaeeum.png?size=50x50&set=set1",
    lastActivityAt: "1716488390000",
    lastMessage:
      "id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est",
    hasSeenLastMessage: false,
    unreadCount: 59,
  },
  {
    id: 26,
    firstName: "Adelind",
    lastName: "Carswell",
    email: "acarswellp@un.org",
    profilePhoto:
      "https://robohash.org/nullasuscipitexercitationem.png?size=50x50&set=set1",
    lastActivityAt: "1714751651000",
    lastMessage:
      "nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque",
    hasSeenLastMessage: true,
    unreadCount: 99,
  },
  {
    id: 27,
    firstName: "Gerek",
    lastName: "McIsaac",
    email: "gmcisaacq@princeton.edu",
    profilePhoto:
      "https://robohash.org/ducimusquirerum.png?size=50x50&set=set1",
    lastActivityAt: "1693406224000",
    lastMessage:
      "lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula",
    hasSeenLastMessage: true,
    unreadCount: 66,
  },
  {
    id: 28,
    firstName: "Sheila",
    lastName: "Guthrum",
    email: "sguthrumr@nytimes.com",
    profilePhoto:
      "https://robohash.org/voluptatesquoaut.png?size=50x50&set=set1",
    lastActivityAt: "1706907830000",
    lastMessage:
      "quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare",
    hasSeenLastMessage: false,
    unreadCount: 52,
  },
  {
    id: 29,
    firstName: "Saul",
    lastName: "Parades",
    email: "sparadess@woothemes.com",
    profilePhoto:
      "https://robohash.org/similiqueesseut.png?size=50x50&set=set1",
    lastActivityAt: "1720188502000",
    lastMessage:
      "ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi",
    hasSeenLastMessage: true,
    unreadCount: 62,
  },
  {
    id: 30,
    firstName: "Dosi",
    lastName: "Brixham",
    email: "dbrixhamt@noaa.gov",
    profilePhoto:
      "https://robohash.org/quiaoptiopariatur.png?size=50x50&set=set1",
    lastActivityAt: "1712872655000",
    lastMessage:
      "ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce",
    hasSeenLastMessage: true,
    unreadCount: 33,
  },
];

export const MESSAGES: Message[] = [
  {
    id: 1,
    chatId: 101,
    content: "Hey, how are you doing?",
    sentAt: "2024-08-17T10:30:00Z",
    sender: 1,
    updatedAt: "2024-08-17T10:32:00Z",
  },
  {
    id: 2,
    chatId: 101,
    content: "I'm doing well, thanks! How about you?",
    sentAt: "2024-08-17T10:31:00Z",
    sender: 2,
    updatedAt: "2024-08-17T10:33:00Z",
  },
  {
    id: 3,
    chatId: 102,
    content: "Can you send me the report?",
    sentAt: "2024-08-17T11:15:00Z",
    sender: 3,
    updatedAt: "2024-08-17T11:17:00Z",
  },
  {
    id: 4,
    chatId: 103,
    content: "Sure, I'll get it to you by EOD.",
    sentAt: "2024-08-17T11:20:00Z",
    sender: 4,
    updatedAt: "2024-08-17T11:22:00Z",
  },
  {
    id: 5,
    chatId: 104,
    content: "Are we still on for the meeting tomorrow?",
    sentAt: "2024-08-17T12:00:00Z",
    sender: 5,
    updatedAt: "2024-08-17T12:05:00Z",
  },
  {
    id: 6,
    chatId: 104,
    content: "Yes, looking forward to it.",
    sentAt: "2024-08-17T12:10:00Z",
    sender: 6,
    updatedAt: "2024-08-17T12:12:00Z",
  },
  {
    id: 7,
    chatId: 105,
    content: "Let’s reschedule our call.",
    sentAt: "2024-08-17T13:00:00Z",
    sender: 7,
    updatedAt: "2024-08-17T13:05:00Z",
  },
  {
    id: 8,
    chatId: 105,
    content: "Sure, what time works for you?",
    sentAt: "2024-08-17T13:10:00Z",
    sender: 8,
    updatedAt: "2024-08-17T13:12:00Z",
  },
  {
    id: 9,
    chatId: 106,
    content: "Can you review the document I sent?",
    sentAt: "2024-08-17T14:00:00Z",
    sender: 9,
    updatedAt: "2024-08-17T14:05:00Z",
  },
  {
    id: 10,
    chatId: 106,
    content: "Yes, I'll get back to you shortly.",
    sentAt: "2024-08-17T14:10:00Z",
    sender: 10,
    updatedAt: "2024-08-17T14:15:00Z",
  },
  {
    id: 9,
    chatId: 106,
    content: "Can you review the document I sent?",
    sentAt: "2024-08-17T14:00:00Z",
    sender: 9,
    updatedAt: "2024-08-17T14:05:00Z",
  },
  {
    id: 10,
    chatId: 106,
    content: "Yes, I'll get back to you shortly.",
    sentAt: "2024-08-17T14:10:00Z",
    sender: 10,
    updatedAt: "2024-08-17T14:15:00Z",
  },
  {
    id: 9,
    chatId: 106,
    content: "Can you review the document I sent?",
    sentAt: "2024-08-17T14:00:00Z",
    sender: 9,
    updatedAt: "2024-08-17T14:05:00Z",
  },
  {
    id: 10,
    chatId: 106,
    content: "Yes, I'll get back to you shortly.",
    sentAt: "2024-08-17T14:10:00Z",
    sender: 10,
    updatedAt: "2024-08-17T14:15:00Z",
  },
  {
    id: 9,
    chatId: 106,
    content: "Can you review the document I sent?",
    sentAt: "2024-08-17T14:00:00Z",
    sender: 9,
    updatedAt: "2024-08-17T14:05:00Z",
  },
  {
    id: 10,
    chatId: 106,
    content: "Yes, I'll get back to you shortly.",
    sentAt: "2024-08-17T14:10:00Z",
    sender: 10,
    updatedAt: "2024-08-17T14:15:00Z",
  },
  {
    id: 9,
    chatId: 106,
    content: "Can you review the document I sent?",
    sentAt: "2024-08-17T14:00:00Z",
    sender: 9,
    updatedAt: "2024-08-17T14:05:00Z",
  },
  {
    id: 10,
    chatId: 106,
    content: "Yes, I'll get back to you shortly.",
    sentAt: "2024-08-17T14:10:00Z",
    sender: 10,
    updatedAt: "2024-08-17T14:15:00Z",
  },
  {
    id: 9,
    chatId: 106,
    content: "Can you review the document I sent?",
    sentAt: "2024-08-17T14:00:00Z",
    sender: 9,
    updatedAt: "2024-08-17T14:05:00Z",
  },
  {
    id: 10,
    chatId: 106,
    content: "Yes, I'll get back to you shortly.",
    sentAt: "2024-08-17T14:10:00Z",
    sender: 10,
    updatedAt: "2024-08-17T14:15:00Z",
  },
];
